Add new actual app + theme implementation
G12-Wanderwave/Wanderwave pull request #16
Opened 2024-03-19 10:39 UTC by KlaKalma

- Implement the app framework with android studio
- Change gitignore to handle local folders
- Add the theme (for now only dark mode)

2024-03-19 18:41 UTC, joriba approved these changes
lgtm

2024-03-19 19:10 UTC, joriba requested changes
run ktfmt to update indentation to 4 spaces consistently in all kotlin files

2024-03-19 19:10 UTC, joriba commented on app/src/main/java/ch/epfl/cs311/wanderwave/ui/App.kt
Incorrect formatting (4 spaces)

2024-03-19 19:10 UTC, joriba commented on app/src/main/java/ch/epfl/cs311/wanderwave/ui/theme/Type.kt
Here too, 4 spaces

2024-03-19 19:10 UTC, joriba commented on gradle/wrapper/gradle-wrapper.properties
Carriage returns - do we care about consistency there?

2024-03-20 11:55 UTC, joriba approved these changes
Seems good now after ktfmt run

2024-03-20 11:59 UTC, KlaKalma reviewed
Lgtm

2024-03-20 12:01 UTC, merged