End to end test/profile screen
G12-Wanderwave/Wanderwave pull request #181
Opened 2024-04-21 19:44 UTC by mbouaissi

This test the fact that the user login, arrive at the main screen, then goes in the profile screen, then goes in the select a song screen, select a song, and goes back to the main screen. 

closes #174

2024-04-21 21:06 UTC, KlaKalma requested changes
Nice code, thanks for being the first one to tackle an end-to-end test and have everything working so we can get inspiration. There seem to be some code that is not related to the test. Probably from another of your branches. I put some comments on things I think are good to change. Thanks for your work

2024-04-21 21:06 UTC, KlaKalma commented on app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModelTest.kt
> +    Log.d("fwefewfew", viewModel.songLists.value.first().tracks.toString())
Use copilot for this, it's very usefull to have the logs having the right title and not something random like this. Can you change it ?

2024-04-21 21:06 UTC, KlaKalma commented on app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/SelectSongScreen.kt
> +  LaunchedEffect(Unit) { viewModel.retrieveAndAddSubsection(CoroutineScope(Dispatchers.IO)) }
why not the view model scope ? Why do you need this ?

2024-04-21 21:06 UTC, KlaKalma commented on app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModel.kt
> +    scope.launch {
Is it important that you send the scope ? Seems a bit weird that you control this from the other screen. This is just a question, there probably is a reason, but just to know

2024-04-22 11:54 UTC, mbouaissi commented on app/src/androidTest/java/ch/epfl/cs311/wanderwave/endToEnd/LoginAndAddSong.kt
> +  @RelaxedMockK private lateinit var profileRepositoryImpl: ProfileRepositoryImpl
idk what we are going to use, so i let it like this for now

2024-04-22 11:56 UTC, KlaKalma commented on app/src/androidTest/java/ch/epfl/cs311/wanderwave/endToEnd/LoginAndAddSong.kt
> +  @RelaxedMockK private lateinit var profileRepositoryImpl: ProfileRepositoryImpl
It's fine I'll delete it when we merge

2024-04-22 12:51 UTC, merged