Feature/profile integration/main
G12-Wanderwave/Wanderwave pull request #235
Opened 2024-05-01 16:37 UTC by mbouaissi

This merge the fully integrated profile to the main

2024-05-01 19:12 UTC, IB-12 requested changes
Overall very good work (as usual), your code is clear and well documented. I wasn't sure which specific files were relevant to the PR so I reviewed everything, which means that some of my comments may not be relevant to you.

2024-05-01 19:12 UTC, IB-12 commented on app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt
>      if (beaconId != null) {
Nice to see you added those null checks we discussed

2024-05-01 19:12 UTC, IB-12 commented on app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt
> +                  //                  Track("b", "Take on me", "A-ha"),
Commented code

2024-05-01 19:12 UTC, IB-12 commented on app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt
> +  val slowScrollAnimation: AnimationSpec<Float> = TweenSpec(durationMillis = 5000, easing = { it })
Might be worth having things such as `durationMillis` be setup as global constants, I think it'll help us have a coherent interface in the long run

2024-05-01 19:12 UTC, IB-12 commented on app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt
> +  val slowScrollAnimation: AnimationSpec<Float> = TweenSpec(durationMillis = 5000, easing = { it })
Same thing for the two delays below

2024-05-01 19:12 UTC, IB-12 commented on app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/ProfileScreen.kt
> +          } // Spacer to create space between Box and VisitCard
Am I missing something or is the spacer not there anymore ?

2024-05-01 19:12 UTC, IB-12 commented on app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/ProfileViewOnlyScreen.kt
> +          // TODO: modify this, because the profile.songLists is not available
Might be worth creating an issue for this so that we don't forget it

2024-05-01 19:12 UTC, IB-12 commented on app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/BeaconViewModel.kt
>          Beacon(
Is there a particular reason for creating this dummy beacon everytime ? Can't we just have a Beacon? initialized to null that we update once the actual value is available ?

2024-05-01 19:12 UTC, IB-12 commented on app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModel.kt
> +    private val repository: ProfileRepository, // TODO revoir
Not sure what you wanted to double check here but I'll leave this comment as a reminder just in case

2024-05-01 20:49 UTC, KlaKalma requested changes
I think we cannot merge this into the main. Can you tell me why the beacon connection is all commented out and the spotify controler as well ? There is a problem with the rebase or something because this shouldn't be. And I saw a few files that were problematic as well, do you know what happened ? One solution and I know it's not a small one, especially when the PR is this close to being finished is to cherry pick the changes with a clean new branch. Because there may be many problems if we merge this branch now in the state it is now.

2024-05-02 06:36 UTC, mbouaissi commented
Sure, I can tell you why the beacon connection is commented. It has been 2 weeks since the dataclass has been changed, and you were assigned to the task to Adapt the database connection to the new beacon types #220, but when I actually see the code, you haven't done it yet, and the MS2 is tomorrow. For the cherry-pick, I am not going to do it, because for my last PR you have reviewed, you ask me to rebase, but at the end, I haven't seen any change, I have just lost my time.

2024-05-02 18:20 UTC, joriba commented
Does displaying the profile on the beacon screen actually work for you? When I click on the "Vortex" beacon from the map, I don't see any tracks displayed, although I have updated the beacon in the database to fit the correct schema...

2024-05-02 18:40 UTC, KlaKalma commented
> Does displaying the profile on the beacon screen actually work for you? When I click on the "Vortex" beacon from the map, I don't see any tracks displayed, although I have updated the beacon in the database to fit the correct schema...

Was a problem with the firebase entity, the software was working perfectly, and the track was indeed the wrong format.

2024-05-02 21:13 UTC, IB-12 approved these changes
Already had reviewed most of it before, and the changes are in line with what we've discussed as a group. Well done 👍

2024-05-02 21:13 UTC, mbouaissi commented
thank you guys for your review <3

2024-05-02 21:13 UTC, merged

2024-05-02 21:14 UTC, KlaKalma reviewed
after the most archaic journey for this pull request lgtm