Modified the add track to beacon UI
G12-Wanderwave/Wanderwave pull request #344
Opened 2024-05-18 16:04 UTC by IB-12

Reorganized the buttons and made the UI adapt to the viewmodel state

2024-05-18 18:55 UTC, mbouaissi requested changes
thx for this, can you also make so that there is only one plus button (if possible ofc)

2024-05-19 11:32 UTC, KlaKalma requested changes
Nice job, I'll try to do the back end as soon as possible !

2024-05-19 11:32 UTC, KlaKalma commented on app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt
> +              Log.d("AddTrack", "Adding track to beacon ${viewModel.beaconId}")
Maybe delete these, no ?

2024-05-19 11:33 UTC, IB-12 commented on app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt
> +              Log.d("AddTrack", "Adding track to beacon ${viewModel.beaconId}")
Will do

2024-05-19 11:34 UTC, IB-12 commented
@KlaKalma Wdym by backend ? I already did it in #337

2024-05-19 11:35 UTC, KlaKalma commented
> @KlaKalma Wdym by backend ? I already did it in #337

Yep sorry for the mistake I thought this was the add and ban track from the profile. Sorry for that.

2024-05-19 11:47 UTC, KlaKalma approved these changes
Good sir !

2024-05-19 11:47 UTC, IB-12 commented
Thanks !

2024-05-19 11:58 UTC, merged